### ISSUE TITLE
LevelDB vs file?

### ISSUE THREAD

**Issue by mgerlach-klick** [replikativ/datahike#14]
When would I use leveldb vs a direct file? What are the implications of each?

**Comment by whilo** [comment]
Good question. The advantage of leveldb is that it does not use separate files for each tree fragment. I would not use leveldb in general, but if you have very large databases it might perform better instead of thousands of small files in a filesystem folder. It largely depends on the filesystem.

**Comment by mgerlach-klick** [comment]
Thanks! What's a 'very large database' for you (seeing how after 'a few million entities at most' one should switch to Datomic, and with what filesystems should or should one not use leveldb vs files?

**Comment by whilo** [comment]
Larger than what I have encountered so far :). I have had the problem in replikativ with filestore vs. leveldb, but there the granularity of associated values was finer, so I was hitting the limits earlier (already for 100000 write operations). Since we pack at least one hundred datoms per tree node at the moment, this would mean more than 10 million datoms by analogy, but I have not tried yet. I will close this for now, feel free to comment further if you have questions.
