### ISSUE TITLE
Improve the config debug logging

### ISSUE THREAD

**Issue by mokshasoft** [replikativ/datahike#263]
This line prints the whole config, including the password that is part of the config when using the JDBC backend.

https://github.com/replikativ/datahike/blob/11b6be4fd4e36ec77500839ffff8a0873f16053a/src/datahike/config.cljc#L127

The line could be changed to:
(log/debug "Using config " (update-in merged-config [:store] dissoc :password))

Or is there a better way to supply the password?

**Comment by TimoKramer** [comment]
You could set the logging to a higher level as well. Or do you think it should still not log the whole config?

**Comment by mokshasoft** [comment]
I have, as far as I know, not set the logging level in my project and it seems like :debug is the default value in timbre. I don't think that it is good to print out passwords to logs by default. I also don't know what is customary, but I would either not print it or change the default datahike log-level to info, and/or change the password printing to :trace.
In our project I'll set the level to :info for now.

**Comment by TimoKramer** [comment]
The level of logging is set in the logging implementation. That has to be done in the project that uses datahike as a library. 

Please have a look here: https://github.com/replikativ/datahike/blob/35e9710be3f22cf9b1e2af7fcf504fb91990f9bd/doc/logging_and_error_handling.md

Since I don't like the current logging of the config as well, I am rephrasing the issue and will change this soonish to something nicer.

Thanks for discussing this with me. Always appreciated. @mokshasoft

**Comment by TimoKramer** [comment]
@mokshasoft PR is up

**Comment by mokshasoft** [comment]
Great!
