### ISSUE TITLE
create record for config

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike#82]

**Comment by TimoKramer** [comment]
1. read config from file
  - storage connection
  - schema
1. merge config with envvars
1. validate config
1. save config to record

**Comment by TimoKramer** [comment]
priorities of config:
1. defaults
1. file
1. env
1. connect arguments
file, env and connect arguments are optional and via defaults there will be running an in-memory store

**Comment by TimoKramer** [comment]
```
{:store {}
 :schema {}}
```
will be top level configs for now, like the corresponding namespaces

**Comment by TimoKramer** [comment]
how to do it in cljs?

**Comment by whilo** [comment]
Hey Timo! Thanks for working on this. Ideally the data structure for the config should look the same in cljs. What do you mean exactly?

**Comment by TimoKramer** [comment]
I think it should have the same structure...I was referencing my problem with knowing nothing about how to handle any kind of env in js/node. I switched to using https://github.com/weavejester/environ for now, because it hopefully just works there. It seems to consider the usage in clj and cljs at least.
